// Sabine
// Configuration File
//---------------------------------------------------------------------------

// Reference Table
// 
// The versions listed for "Client", "Athena", and "Sabine" refer
// to versions found in the client, the Athena packet db, and Sabine
// respectively. Only the Sabine packet version is relevant for this
// server, the others are for reference only.
// 
// Supported versions/clients:
// |----------------------|------------|--------|--------|--------|
// | Name                 | Exe Date   | Client | Athena | Sabine |
// |----------------------|------------|--------|--------|--------|
// | iRO Alpha            | 2001-08-30 | -      | -      | 100    |
// |----------------------|------------|--------|--------|--------|
// 
// Other known clients:
// |----------------------|------------|--------|--------|--------|
// | Name                 | Exe Date   | Client | Athena | Sabine |
// |----------------------|------------|--------|--------|--------|
// | iRO Beta1            | 2002-02-20 | 2      | -      | 200    |
// | jRO Beta2            | 2002-08-09 | 3      | -      | 300    |
// | iRO EP4              | 2003-04-30 | -      | -      | 350    |
// | jRO EP3              | 2003-05-27 | -      | -      | 400    |
// | iRO EP6              | 2003-10-31 | 18     | -      | 500    |
// | euRO EP4-5           | 2004-05-12 | 1      | ?      | 600    |
// | iRO EP8              | 2004-08-03 | 1      | 6      | 700    |
// | bRO EP8              | 2004-12-28 | 1      | 14     | 800    |
// | euRO EP10            | 2007-03-05 | 1      | 20     | 2000   |
// |----------------------|------------|--------|--------|--------|
// 
// Some of the known clients might work with the server, but they
// aren't officially supported yet.

// Packet version to use. Affects client compatibility and certain,
// typically client-dependend, features.
packet_version: 100

include "/user/conf/version.conf"
