// Sabine
// Configuration File
//---------------------------------------------------------------------------

// If disabled, actions such as sitting and trading can be done
// without the necessary Basic Skill levels.
// Default: yes
check_basic_skills: yes

include "/user/conf/world/skills.conf"
